In [1]:
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt 
sb.set()
from dython import nominal
from dython import nominal

In [2]:
data = pd.read_csv('model_dat.csv')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9846 entries, 0 to 9845
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Brand             9846 non-null   object
 1   Year              9846 non-null   int64
 2   Horsepower        9846 non-null   int64
 3   Engine Cylinders  9846 non-null   int64
 4   Number of Doors   9846 non-null   int64
 5   Price             9846 non-null   int64
dtypes: int64(5), object(1)
memory usage: 461.7+ KB

In [4]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso , LogisticRegression
from sklearn.neighbors import KNeighborsRegressor , KNeighborsClassifier
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor ,RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [5]:
def model_catagorical(TargetVariable , Predictors):   
    X=data[Predictors].values
    y=data[TargetVariable].values

    # Split the data into training and testing set
    from sklearn.model_selection import train_test_split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

    training_models = {
        #"                     Logistic Regression": LogisticRegression(),
        "                           Naive Bayes": GaussianNB(),
        "        Linear Discrimination Analysis": LinearDiscriminantAnalysis(),
        "                   K-Nearest Neighbors": KNeighborsClassifier(),
        "                         Decision Tree": DecisionTreeClassifier(),
        "                         Random Forest": RandomForestClassifier(),
       # "               Support Vector Machines": svm.SVC;
    }

    for name, training_model in training_models.items():
        training_model.fit(X_train, y_train.ravel())
        print(name + " trained.")
    print("\n")
    for name, training_model in training_models.items():
        print(name + " R^2 Score: {:.5f}".format(training_model.score(X_test, y_test)))

In [17]:
model_catagorical('Price' , ['Engine Cylinders'])

                           Naive Bayes trained.
        Linear Discrimination Analysis trained.
                   K-Nearest Neighbors trained.
                         Decision Tree trained.
                         Random Forest trained.


                           Naive Bayes R^2 Score: 0.00203
        Linear Discrimination Analysis R^2 Score: 0.08274
                   K-Nearest Neighbors R^2 Score: 0.03604
                         Decision Tree R^2 Score: 0.08274
                         Random Forest R^2 Score: 0.08274

In [6]:
model_catagorical('Price' , ['Year'])

                           Naive Bayes trained.
        Linear Discrimination Analysis trained.
                   K-Nearest Neighbors trained.
                         Decision Tree trained.
                         Random Forest trained.


                           Naive Bayes R^2 Score: 0.00051
        Linear Discrimination Analysis R^2 Score: 0.07005
                   K-Nearest Neighbors R^2 Score: 0.06497
                         Decision Tree R^2 Score: 0.06802
                         Random Forest R^2 Score: 0.06802

In [16]:
model_catagorical('Price' , ['Number of Doors'])

                           Naive Bayes trained.
        Linear Discrimination Analysis trained.
                   K-Nearest Neighbors trained.
                         Decision Tree trained.
                         Random Forest trained.


                           Naive Bayes R^2 Score: 0.00102
        Linear Discrimination Analysis R^2 Score: 0.07614
                   K-Nearest Neighbors R^2 Score: 0.06954
                         Decision Tree R^2 Score: 0.07614
                         Random Forest R^2 Score: 0.07614

In [7]:
# Treating all the nominal variables at once using dummy variables
MLDATA=pd.get_dummies(data)

# Printing sample rows
MLDATA

,Year,Horsepower,Engine Cylinders,Number of Doors,Price,Brand_Acura,Brand_Alfa Romeo,Brand_Audi,Brand_BMW,Brand_Buick,...,Brand_Plymouth,Brand_Pontiac,Brand_Porsche,Brand_Saab,Brand_Scion,Brand_Subaru,Brand_Suzuki,Brand_Toyota,Brand_Volkswagen,Brand_Volvo
0,2011,335,6,2,46135,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2011,300,6,2,40650,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,2011,300,6,2,36350,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,2011,230,6,2,29450,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,2011,230,6,2,34500,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9841,2012,300,6,4,46120,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9842,2012,300,6,4,56670,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9843,2012,300,6,4,50620,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9844,2013,300,6,4,50920,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9845,2006,221,6,4,28995,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
# Printing all the column names for our reference
MLDATA.columns

Index(['Year', 'Horsepower', 'Engine Cylinders', 'Number of Doors', 'Price',
       'Brand_Acura', 'Brand_Alfa Romeo', 'Brand_Audi', 'Brand_BMW',
       'Brand_Buick', 'Brand_Cadillac', 'Brand_Chevrolet', 'Brand_Chrysler',
       'Brand_Dodge', 'Brand_FIAT', 'Brand_Ford', 'Brand_GMC', 'Brand_Genesis',
       'Brand_HUMMER', 'Brand_Honda', 'Brand_Hyundai', 'Brand_Infiniti',
       'Brand_Kia', 'Brand_Land Rover', 'Brand_Lexus', 'Brand_Lincoln',
       'Brand_Lotus', 'Brand_Maserati', 'Brand_Mazda', 'Brand_Mercedes-Benz',
       'Brand_Mitsubishi', 'Brand_Nissan', 'Brand_Oldsmobile',
       'Brand_Plymouth', 'Brand_Pontiac', 'Brand_Porsche', 'Brand_Saab',
       'Brand_Scion', 'Brand_Subaru', 'Brand_Suzuki', 'Brand_Toyota',
       'Brand_Volkswagen', 'Brand_Volvo'],
      dtype='object')

In [9]:
def model_regression(TargetVariable , Predictors):

    X=MLDATA[Predictors].values
    y=MLDATA[TargetVariable].values

    # Split the data into training and testing set
    from sklearn.model_selection import train_test_split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

    training_models = {
        "                     Linear Regression": LinearRegression(),
        " Linear Regression (L2 Regularization)": Ridge(),
        " Linear Regression (L1 Regularization)": Lasso(),
        "                   K-Nearest Neighbors": KNeighborsRegressor(),
        "                         Decision Tree": DecisionTreeRegressor(),
        "                         Random Forest": RandomForestRegressor(),
        "                     Gradient Boosting": GradientBoostingRegressor()
    }

    for name, training_model in training_models.items():
        training_model.fit(X_train, y_train)
        print(name + " trained.")
    print("\n")
    for name, training_model in training_models.items():
        print(name + " R^2 Score: {:.5f}".format(training_model.score(X_test, y_test)))

In [10]:
model_regression('Price',['Year', 'Horsepower', 'Engine Cylinders', 'Number of Doors',
       'Brand_Acura', 'Brand_Alfa Romeo', 'Brand_Audi', 'Brand_BMW',
       'Brand_Buick', 'Brand_Cadillac', 'Brand_Chevrolet', 'Brand_Chrysler',
       'Brand_Dodge', 'Brand_FIAT', 'Brand_Ford', 'Brand_GMC', 'Brand_Genesis',
       'Brand_HUMMER', 'Brand_Honda', 'Brand_Hyundai', 'Brand_Infiniti',
       'Brand_Kia', 'Brand_Land Rover', 'Brand_Lexus', 'Brand_Lincoln',
       'Brand_Lotus', 'Brand_Maserati', 'Brand_Mazda', 'Brand_Mercedes-Benz',
       'Brand_Mitsubishi', 'Brand_Nissan', 'Brand_Oldsmobile',
       'Brand_Plymouth', 'Brand_Pontiac', 'Brand_Porsche', 'Brand_Saab',
       'Brand_Scion', 'Brand_Subaru', 'Brand_Suzuki', 'Brand_Toyota',
       'Brand_Volkswagen', 'Brand_Volvo'])

                     Linear Regression trained.
 Linear Regression (L2 Regularization) trained.
 Linear Regression (L1 Regularization) trained.
                   K-Nearest Neighbors trained.
                         Decision Tree trained.
                         Random Forest trained.
                     Gradient Boosting trained.


                     Linear Regression R^2 Score: 0.80514
 Linear Regression (L2 Regularization) R^2 Score: 0.80514
 Linear Regression (L1 Regularization) R^2 Score: 0.80526
                   K-Nearest Neighbors R^2 Score: 0.90454
                         Decision Tree R^2 Score: 0.93258
                         Random Forest R^2 Score: 0.93508
                     Gradient Boosting R^2 Score: 0.90091

In [11]:
model_regression('Price',['Year'])

                     Linear Regression trained.
 Linear Regression (L2 Regularization) trained.
 Linear Regression (L1 Regularization) trained.
                   K-Nearest Neighbors trained.
                         Decision Tree trained.
                         Random Forest trained.
                     Gradient Boosting trained.


                     Linear Regression R^2 Score: 0.47282
 Linear Regression (L2 Regularization) R^2 Score: 0.47282
 Linear Regression (L1 Regularization) R^2 Score: 0.47282
                   K-Nearest Neighbors R^2 Score: 0.34906
                         Decision Tree R^2 Score: 0.51377
                         Random Forest R^2 Score: 0.51368
                     Gradient Boosting R^2 Score: 0.51376

In [12]:
model_regression('Price',['Horsepower'])

                     Linear Regression trained.
 Linear Regression (L2 Regularization) trained.
 Linear Regression (L1 Regularization) trained.
                   K-Nearest Neighbors trained.
                         Decision Tree trained.
                         Random Forest trained.
                     Gradient Boosting trained.


                     Linear Regression R^2 Score: 0.57001
 Linear Regression (L2 Regularization) R^2 Score: 0.57001
 Linear Regression (L1 Regularization) R^2 Score: 0.57001
                   K-Nearest Neighbors R^2 Score: 0.59954
                         Decision Tree R^2 Score: 0.65798
                         Random Forest R^2 Score: 0.66442
                     Gradient Boosting R^2 Score: 0.64131

In [13]:
model_regression('Price',['Engine Cylinders'])

                     Linear Regression trained.
 Linear Regression (L2 Regularization) trained.
 Linear Regression (L1 Regularization) trained.
                   K-Nearest Neighbors trained.
                         Decision Tree trained.
                         Random Forest trained.
                     Gradient Boosting trained.


                     Linear Regression R^2 Score: 0.09891
 Linear Regression (L2 Regularization) R^2 Score: 0.09891
 Linear Regression (L1 Regularization) R^2 Score: 0.09891
                   K-Nearest Neighbors R^2 Score: -0.01767
                         Decision Tree R^2 Score: 0.11847
                         Random Forest R^2 Score: 0.11840
                     Gradient Boosting R^2 Score: 0.11847

In [14]:
model_regression('Price',['Number of Doors'])

                     Linear Regression trained.
 Linear Regression (L2 Regularization) trained.
 Linear Regression (L1 Regularization) trained.
                   K-Nearest Neighbors trained.
                         Decision Tree trained.
                         Random Forest trained.
                     Gradient Boosting trained.


                     Linear Regression R^2 Score: 0.04013
 Linear Regression (L2 Regularization) R^2 Score: 0.04013
 Linear Regression (L1 Regularization) R^2 Score: 0.04013
                   K-Nearest Neighbors R^2 Score: -0.02798
                         Decision Tree R^2 Score: 0.05093
                         Random Forest R^2 Score: 0.05093
                     Gradient Boosting R^2 Score: 0.05093

In [15]:
model_regression(TargetVariable='Price',Predictors=['Brand_Acura', 'Brand_Alfa Romeo', 'Brand_Audi', 'Brand_BMW',
       'Brand_Buick', 'Brand_Cadillac', 'Brand_Chevrolet', 'Brand_Chrysler',
       'Brand_Dodge', 'Brand_FIAT', 'Brand_Ford', 'Brand_GMC', 'Brand_Genesis',
       'Brand_HUMMER', 'Brand_Honda', 'Brand_Hyundai', 'Brand_Infiniti',
       'Brand_Kia', 'Brand_Land Rover', 'Brand_Lexus', 'Brand_Lincoln',
       'Brand_Lotus', 'Brand_Maserati', 'Brand_Mazda', 'Brand_Mercedes-Benz',
       'Brand_Mitsubishi', 'Brand_Nissan', 'Brand_Oldsmobile',
       'Brand_Plymouth', 'Brand_Pontiac', 'Brand_Porsche', 'Brand_Saab',
       'Brand_Scion', 'Brand_Subaru', 'Brand_Suzuki', 'Brand_Toyota',
       'Brand_Volkswagen', 'Brand_Volvo'])

                     Linear Regression trained.
 Linear Regression (L2 Regularization) trained.
 Linear Regression (L1 Regularization) trained.
                   K-Nearest Neighbors trained.
                         Decision Tree trained.
                         Random Forest trained.
                     Gradient Boosting trained.


                     Linear Regression R^2 Score: 0.24409
 Linear Regression (L2 Regularization) R^2 Score: 0.24325
 Linear Regression (L1 Regularization) R^2 Score: 0.24331
                   K-Nearest Neighbors R^2 Score: 0.03975
                         Decision Tree R^2 Score: 0.24410
                         Random Forest R^2 Score: 0.24353
                     Gradient Boosting R^2 Score: 0.23056

### We can see when the features are used individually, the accuracy is very low. However, when they are all combined, the accuracy is greatly increased (From 0% to 60% to 80%-90%)